# This is a config for E2B sandbox template.
# You can use template ID (kj39q4q7oj77ny8nwnr7) or template name (vibe-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-test2')

team_id = "3bed8087-fe7a-4a72-92c2-9bf973cf8016"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-test2"
template_id = "kj39q4q7oj77ny8nwnr7"
